---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
  labels:
    app: python-app
    test: test
  annotations:
    fluxcd.io/tag.example-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: manug2018/python:1.0.0
        env:
        - name: CALC_SERVICE_IP
          value: CALC_SERVICE_IP_VALUE
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
