apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-app
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000

apiVersion: v1
kind: Service
metadata:
  name: calc-service
  labels:
    app: calc-service-app
spec:
  type: LoadBalancer
  selector:
    app: calc-service-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000